# Generated by Django 4.2.3 on 2023-07-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='orientacion',
        ),
    ]
