# Generated by Django 4.2.3 on 2023-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0002_remove_curso_orientacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nota',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
