# Generated by Django 4.2.3 on 2023-07-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0003_estudiante_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nota',
            field=models.IntegerField(blank=True),
        ),
    ]
