# Generated by Django 4.2.3 on 2023-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_estudios', '0004_alter_estudiante_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
